# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "canonical-ubuntu-12.04"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.define "myserver1" do |myserver1|
   myserver1.vm.hostname = "myserver1"
   myserver1.vm.network :private_network, ip: "33.33.33.111"
   myserver1.vm.network :public_network
   myserver1.vm.provision :chef_solo do |chef|
    chef.json = {
     :java => {:jdk_version  => "7"}

     }

    chef.run_list = [
        "recipe[java]",
        "recipe[logrotate]",
        "recipe[wildfly-clu::default]",
        "recipe[wildfly-clu::logs]",
        "recipe[wildfly-clu::domain]"

    ]
   end
  end

  config.vm.define "myserver2" do |myserver2|
   myserver2.vm.hostname = "myserver2"
   myserver2.vm.network :private_network, ip: "33.33.33.112"
   myserver2.vm.network :public_network
   myserver2.vm.provision :chef_solo do |chef|
    chef.json = {
     :java => {:jdk_version  => "7"}

     }

    chef.run_list = [
        "recipe[java]",
        "recipe[logrotate]",
        "recipe[wildfly-clu::default]",
        "recipe[wildfly-clu::logs]",
        "recipe[wildfly-clu::domain]"

    ]
  end
 end

  config.vm.define "myserver3" do |myserver3|
   myserver3.vm.hostname = "myserver3"
   myserver3.vm.network :private_network, ip: "33.33.33.113"
   myserver3.vm.network :public_network
   myserver3.vm.provision :chef_solo do |chef|
    chef.json = {
     :java => {:jdk_version  => "7"}

     }

    chef.run_list = [
        "recipe[java]",
        "recipe[logrotate]",
        "recipe[wildfly-clu::default]",
        "recipe[wildfly-clu::logs]",
        "recipe[wildfly-clu::domain]"


 ]
  end
 end


  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    chef.json = {
     :java => {:jdk_version  => "7"}

     }

    chef.run_list = [
        #"recipe[java]",
        #"recipe[wildfly-clu::default]",
        #"recipe[wildfly-clu::logs]",
        #"recipe[wildfly-clu::domain]"
    ]
  end
end
